Repository telegraf/telegraf, pull requests merged in 2020-12, with the labels that each got.

#1195 Leverage unionization
  src/composer.ts
  src/context.ts
  src/stage.ts
  src/telegram-types.ts
  test/composer.js
Labels: help wanted, question, typings

#1215 Add `Composer::guard`
  src/composer.ts
  src/context.ts
  src/core/helpers/string.ts
  src/telegraf.ts
  src/telegram-types.ts
  test/telegraf.js
Labels: breaking, enhancement

#1194 Types and examples for scenes and wizards
  docs/examples/custom-context-bot.ts
  docs/examples/example-bot.ts
  docs/examples/scenes/scenes-bot-custom-context-and-scene-and-scene-session.ts
  docs/examples/scenes/scenes-bot-custom-context-and-scene-session.ts
  docs/examples/scenes/scenes-bot-custom-context-and-scene.ts
  docs/examples/scenes/scenes-bot-custom-context-and-session-and-scene-and-scene-session.ts
  docs/examples/scenes/scenes-bot-custom-context-and-session-and-scene-session.ts
  docs/examples/scenes/scenes-bot-custom-context-and-session-and-scene.ts
  docs/examples/scenes/scenes-bot-custom-context-and-session.ts
  docs/examples/scenes/scenes-bot-custom-context.ts
  docs/examples/scenes/scenes-bot-custom-scene-and-scene-session.ts
  docs/examples/scenes/scenes-bot-custom-scene-session.ts
  docs/examples/scenes/scenes-bot-custom-scene.ts
  docs/examples/scenes/scenes-bot.ts
  docs/examples/wizard-bot.js
  docs/examples/wizards/wizard-bot-custom-context-and-scene-and-scene-session.ts
  docs/examples/wizards/wizard-bot-custom-context-and-scene-session.ts
  docs/examples/wizards/wizard-bot-custom-context-and-scene.ts
  docs/examples/wizards/wizard-bot-custom-context-and-session-and-scene-and-scene-session.ts
  docs/examples/wizards/wizard-bot-custom-context-and-session-and-scene-session.ts
  docs/examples/wizards/wizard-bot-custom-context-and-session-and-scene.ts
  docs/examples/wizards/wizard-bot-custom-context-and-session.ts
  docs/examples/wizards/wizard-bot-custom-context.ts
  docs/examples/wizards/wizard-bot-custom-scene-and-scene-session.ts
  docs/examples/wizards/wizard-bot-custom-scene-session.ts
  docs/examples/wizards/wizard-bot-custom-scene.ts
  docs/examples/wizards/wizard-bot.ts
  src/index.ts
  src/scenes/base.ts
  src/scenes/context.ts
  src/scenes/wizard/context.ts
  src/scenes/wizard/index.ts
  src/session.ts
  src/stage.ts
Labels: typings

#1253 Don't bind `Context` methods
  src/context.ts
Labels: breaking

#1251 Simplify `Middleware`
  src/composer.ts
  src/context.ts
  src/index.ts
  src/middleware.ts
  src/router.ts
  src/scenes/base.ts
  src/scenes/context.ts
  src/scenes/wizard/context.ts
  src/scenes/wizard/index.ts
  src/session.ts
  src/stage.ts
  src/types.ts
Labels: breaking, typings

#1082 Rework and re-enable `webhookReply`
  src/core/network/client.ts
  src/telegraf.ts
  test/telegraf.js
Labels: breaking, bug, typings
