Repository telegraf/telegraf, pull requests merged in 2021-02, with the labels that each got.

#1331 Add `examples/session-bot.ts`
  README.md
  docs/examples/session-bot.ts
  src/session.ts
Labels: docs

#1334 feat(client): add `apiMode` option
  src/core/network/client.ts
Labels: enhancement

#1346 hotfix(client): include base url
  src/core/network/client.ts
  src/telegram.ts
Labels: bug

#1345 Fix koa example
  docs/examples/koa-webhook-bot.js
Labels: docs

#1368 Narrow more getters in `GuardedContext` to future-proof it
  src/composer.ts
  src/context.ts
  src/deunionize.ts
Labels: enhancement, typings

#1378 Fix type of `ctx.from`
  package-lock.json
  package.json
  src/composer.ts
  src/context.ts
  src/telegram-types.ts
Labels: bug
